### ISSUE TITLE
Feature request: Gentoo ebuild

### ISSUE THREAD

**Issue by ghost** [gfduszynski/cm-rgb#12]
Hi. Do you think it would be possible to provide an Gentoo ebuild for your project? It would be really great. Thank you.

**Comment by gfduszynski** [comment]
Hi. I think it's a good idea, but currently I'm not able to handle this. 
I'm sticking to bug fixing for now, however I'll happily accept a pull request :)

**Comment by flipy** [comment]
There is already a Gentoo ebuild on the [flussence ](http://gpo.zugaina.org/app-misc/cm-rgb) overlay, albeit it only pulls version 0.1.
It is easy to add more versions, so if anyone takes ownership I can help.

**Comment by gfduszynski** [comment]
That's great to hear :+1: 
I'll take a look on weekend as I'm not familiar with how any of this works :)

**Comment by gfduszynski** [comment]
If I understand correctly ebuild (cm-rgb-9999) in the overlay provided is a live ebuild. 
Does this pull the latest build on gentoo ? @flipy
