### ISSUE TITLE
leds still on

### ISSUE THREAD

**Issue by jcw1976** [gfduszynski/cm-rgb#15]
I went through the steps to turn off the led light on the fan.  everything went great except the lights are still on. what went wrong?

**Comment by gfduszynski** [comment]
Hi, do other commands work at all for you ?

**Comment by jcw1976** [comment]
The help command works but I have not used another command

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by gfduszynski** [comment]
1. Verify that you have properly connected usb cable to the controller 
2. Check lsusb if you are on linux to verify if the controller is present. Should have something like this: ``Bus 003 Device 004: ID 2516:0051 Cooler Master Co., Ltd. ``
3. Try running ``cm-rgb-cli version`` and please paste the result

**Comment by jcw1976** [comment]
i see the Bus 003 Device 004: ID 2516:0051 Cooler Master Co., Ltd. is present

Usage: cm-rgb-cli [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  add-udev-rule
  restore
  set
  version

when I did this command:

cm-rgb-cli set logo --mode=off save

it ran in the terminal


________________________________

**Comment by gfduszynski** [comment]
Try running ``cm-rgb-cli version``
This will read firmware version from the controller.

**Comment by jcw1976** [comment]
V1.01.00

________________________________

**Comment by gfduszynski** [comment]
Ok, same as mine and comms work.

**Comment by jcw1976** [comment]
im not sure what else to do

________________________________

**Comment by gfduszynski** [comment]
I was thinking :)

Try ``cm-rgb-cli set logo --color=ff0000`` this should set your logo to red.

**Comment by gfduszynski** [comment]
If that does not work run ``cm-rgb-cli restore`` and try to set color again.

**Comment by jcw1976** [comment]
cm-rbg-monitor is the only command that changes the lights

________________________________

**Comment by gfduszynski** [comment]
That's highly unusual. 
Please make sure you don't have any cm-rgb-monitor process running in the 
background. It overwrites color frequently and could make the result of running cm-rgb-cli
not visible.

**Comment by jcw1976** [comment]
when I run cm-rgb-monitor the led blinks from red to orange on the ring of the fan

________________________________

**Comment by jcw1976** [comment]
I looked in system monitor under the tab processes and didn't see any processes that referred to cm-rgb-monitor

________________________________

**Comment by gfduszynski** [comment]
That's strange, both the monitor and the cli use same code to control the led's.
``cm-rgb-cli set logo --mode=breathe --color=#00ff00 --speed=3 --brightness=5 fan --mode=breathe --color=#0000ff --speed=4 --brightness=1 ring --mode=swirl --color=#ff0000 --speed=1 --brightness=1``
This one sets every area of the cooler, let's see if anything happens at all.

**Comment by gfduszynski** [comment]
I've just remembered , do you have second cable connected as well ?
The one to the rgb header ?
It's NOT suppose to be connected or the controller goes bananas on this cooler.

**Comment by jcw1976** [comment]
when I ran that command it went straight to red and began its process. when I restore it changes it again.  so there is diffidently   changes going on.

________________________________

**Comment by jcw1976** [comment]
I have every wire for the fan hooked up


________________________________

**Comment by gfduszynski** [comment]
Ok, that may be it 
![image](https://user-images.githubusercontent.com/1913102/77576640-d0e55000-6ed5-11ea-8fc7-3c65df707e07.png)
(Please note: this is random image from the internets and arrows are also not placed by me)

I recommend only having the one responsible for the USB connected.

**Comment by jcw1976** [comment]
ok i'll shut down and disconnect the wire on the right, under the fan and I will let you know if that works

________________________________

**Comment by jcw1976** [comment]
The USB port coming out of the fan is the one on the right with the three wires.  The one on the left has four wires and that is for the RGB for my setup


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by gfduszynski** [comment]
How is it going ?

**Comment by jcw1976** [comment]
I disconnected the RGB cable and I left the USB cable and I have no RGB at all I tried to restore it via cm-rgb-restore and it still is off so I'm guessing your software runs through the RGB cable and not the USB

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jcw1976** [comment]
I think I'm just going to unplug both USB and RGB it seems like those are both for just RGB and does not have any effect on the control of the fan if I'm correct because my fan control is through the BIOS on my motherboard

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by gfduszynski** [comment]
It's most certainly through the USB. Most likely the command that you have sent earlier with  the ``save`` actually has been stored :)

**Comment by jcw1976** [comment]
How can I check it how can I turn it back on

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by gfduszynski** [comment]
Try ``cm-rgb-cli set logo --color=ff0000``

**Comment by jcw1976** [comment]
Never mind I figured it out you are right thanks for your help

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gfduszynski** [comment]
No problem, I'm glad it has worked out for you :+1:

**Comment by jcw1976** [comment]
I turned it back on and then I turned it back off it works

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jcw1976** [comment]
I have one other problem if you're willing I have a Nvidia GeForce RTX 2080 TI founders edition graphics card and I want to shut off the logo LED do you have any hints?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gfduszynski** [comment]
Those are a bit of pain, same with AMD. I've set mine on windows and it remembers the settings.
It's quite risky to touch this (with random software) as the bus that controls the leds on graphics cards often have critical hardware components on the same bus. There is a chance of damaging the card.

**Comment by jcw1976** [comment]
I'll leave it alone then.  It's okay to have the RGB off of the fan we just worked on though right

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jcw1976** [comment]
It's okay with what we did and keeping the RGB off of the family worked on right nothing's going to break?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gfduszynski** [comment]
It's independent of the actual fan so cooling will be ok.
I didn't have any complaints yet :)

**Comment by jcw1976** [comment]
cool thanks

________________________________
