### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by batinyarkan** [gfduszynski/cm-rgb#19]
Greetings. cm-rgb: command not found is what I'm getting even before trying to give USB access to the script. What might be the reason if may I ask? (I'm quite new around here)

**Comment by gfduszynski** [comment]
Hi,
Did you ran ``pip install cm-rgb`` with ``sudo`` or without ?

**Comment by gfduszynski** [comment]
Btw. just to be 100% sure the actual command is ``cm-rgb-cli`` not ``cm-rgb``

**Comment by batinyarkan** [comment]
oh yea, you're right, actually that's not the source, I separately ran cm-rgb-cli it was fine, not main problem creating is sudo: /usr/bin/sh: command not found (right after cm-rgb-cli add-udev-rule) why it's not able to create that you think?

**Comment by gfduszynski** [comment]
When you run add-udev-rule I'm actually trying to execute this:
```
    rule = "SUBSYSTEM==\"usb\", ATTR{idVendor}==\"2516\", ATTR{idProduct}==\"0051\", TAG+=\"uaccess\", TAG+=\"udev-acl\""
    cmd = "/usr/bin/sudo echo '"+rule+"' > /etc/udev/rules.d/60-cm-rgb.rules"
    returncode = subprocess.call(cmd.split())
```

This basically calls ``/usr/bin/sudo echo <rule> > /etc/udev/rules.d/60-cm-rgb.rules``
I think on your distribution sudo may be in different location.
Can you execute ``which sudo`` ?

Any way if you just want to have the rule added it's ok to create the file manually.

**Comment by batinyarkan** [comment]
Actually it's indeed in /usr/bin/sudo. Probably you also understood I'm quite rookie and new to Linux environment and solving things manually. Do you mind me asking how to create which file manually and place it? I genuinely appreciate your effort on answering these..

**Comment by gfduszynski** [comment]
Don't worry we will get this working :)

Last option is probably ``which sh`` 

To create the file yourself use text editor like nano or vi as root like so:
```
sudo nano /etc/udev/rules.d/60-cm-rgb.rules
```

Then paste in:
```
SUBSYSTEM=="usb", ATTR{idVendor}=="2516", ATTR{idProduct}=="0051", TAG+="uaccess", TAG+="udev-acl"
```

This will be exactly like running the command.
Udev should automatically recognize new rule and apply it.
This will allow you to run ``cm-rgb-cli`` and ``cm-rgb-monitor`` without ``sudo``.

**Comment by batinyarkan** [comment]
I think I'm progressing thanks to you incredible help :)

I think I created the file with the name in correct location accurately, saved the line inside the text editor. Now I'm able to call the cm-rgb-cli successfully since it give me the options and list, but when I choose, I get following error;

byarkan@computername:~$ cm-rgb-cli set ring --mode=static --color=#008000
Traceback (most recent call last):
  File "/home/byarkan/.local/bin/cm-rgb-cli", line 151, in <module>
    main_group()
  File "/home/byarkan/.local/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/byarkan/.local/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/byarkan/.local/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/byarkan/.local/lib/python2.7/site-packages/click/core.py", line 1268, in invoke
    Command.invoke(self, ctx)
  File "/home/byarkan/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/byarkan/.local/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/byarkan/.local/lib/python2.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/byarkan/.local/bin/cm-rgb-cli", line 13, in setup_group
    'ctrl': CMRGBController(),
  File "/home/byarkan/.local/lib/python2.7/site-packages/cm_rgb/ctrl.py", line 50, in __init__
    self.__init_hid_device()
  File "/home/byarkan/.local/lib/python2.7/site-packages/cm_rgb/ctrl.py", line 60, in __init_hid_device
    self.device.open_path(device_list[0]["path"])
  File "hid.pyx", line 72, in hid.device.open_path
IOError: open failed

 Could it be I have multiple versions of python where your file is trying to trigger with Python 2 commands where maybe computer is trying to call most recent version I have, Python 3?

**Comment by batinyarkan** [comment]
jesus, accidentally closed..

**Comment by gfduszynski** [comment]
Let's first verify the presence of the usb device:
```
$ lsusb | grep Cooler
Bus 003 Device 003: ID 2516:0051 Cooler Master Co., Ltd. 
```
This the expected output, please verify.

Make sure you have connected the usb cable to the cooler and that the second rgb header cable 
is **not** connected. This a common mistake with this device.

**Comment by batinyarkan** [comment]
Both cable was plugged in (computer store assemblied the PC), with the hope of getting results I removed the RGB cable, now there's only fan power and USB cable connected to fan for sure, but I get nothing out of lsusb | grep Cooler in terminal. Doesn't do anything.

**Comment by batinyarkan** [comment]
byarkan@Zion:~$ lsusb
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 2516:0051  
Bus 001 Device 003: ID 1532:0043 Razer USA, Ltd 
Bus 001 Device 005: ID 1532:0214 Razer USA, Ltd 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by gfduszynski** [comment]
Please try to run ``lsusb`` without grep, perhaps something changed, as it sounds you have a new pc.

**Comment by gfduszynski** [comment]
Thats it :)
Bus 001 Device 004: ID 2516:0051

I'll grab something to eat and return to this.

**Comment by batinyarkan** [comment]
Setup is entirely new. Store assemblied the parts I've listed them, I brought the PC home and install linux. This is the whole story :)

**Comment by batinyarkan** [comment]
Bon appetit! I'm sorry for interrupting even your meal.. I'm quite close to throw the case out of window at this point :D

**Comment by batinyarkan** [comment]
DUDEEEE!!!!! IT WORRRKKSSSS!!!! :D :D :D :D I JUST TRIED THE PREVIOUS CODE! HOLY SMOKES!

**Comment by gfduszynski** [comment]
:D :dancers:
