### ISSUE TITLE
ubuntu 18.04: dependency: libusb-1.0-0-dev

### ISSUE THREAD

**Issue by MichaelHeimann** [gfduszynski/cm-rgb#2]
I needed a "sudo apt-get install libusb-1.0-0-dev" to make "sudo pip install cm-rgb" successful.
Before I always got:

hidapi/libusb/hid.c:47:10: fatal error: libusb.h: Datei oder Verzeichnis nicht gefunden

**Comment by gfduszynski** [comment]
Thank you for reporting.

I've added additional instructions to readme.
