### ISSUE TITLE
Possible to reset to default out-of-package behavior?

### ISSUE THREAD

**Issue by unf** [gfduszynski/cm-rgb#20]
Hi, thanks for that great tool.

I played a little on 2 machines running Ubuntu Focal Fossa. Is there a way to switch back to the out-of-box behavior of the AMD Wraith Prism?

Out-of-box, w/o any intervention and no connection, logo & fan does cycle slowly thru a rainbow cycle and the ring also but with different speed, faster than logo & fan.

Cheers

**Comment by gfduszynski** [comment]
Hi, thank you fo r your kind words :)

Rainbow mode in not supported yet, but this is something that will be possible.
There is an open feature request for this #10 and other modes. 

Other than that it can be done rather painfully through Windows VM and original app.

**Comment by unf** [comment]
Hi, ok, sounds good, will be patient.

And no it's not painful to work with on/with Windows ... every OS has it's character, I prefer to handle all of them instead of complaining ... ^^

**Comment by gfduszynski** [comment]
What I meant is, using VM with USB passthrough to run original app in order reset to factory settings is painful :)
