### ISSUE TITLE
Restoring factory settings

### ISSUE THREAD

**Issue by rafaeln** [gfduszynski/cm-rgb#21]
Hi. Thanks for the great application. It finally allowed me to turn those fan LEDs off and sleep in a darker room. I was wondering if there is a way to restore the factory settings, though.

**Comment by gfduszynski** [comment]
Hi,
Thank you for your kind words :)
Currently the original rainbow mode is not yet supported.
See #20

**Comment by rafaeln** [comment]
I see. Thanks for pointing out the workaround in #20. I have a Win10 VM I can use to restore 🌈 mode in case I decide to hold a rave party in my room.
