### ISSUE TITLE
Feature Request: Allow for faster refresh times in cm-rgb-monitor

### ISSUE THREAD

**Issue by mpsdskd** [gfduszynski/cm-rgb#22]
I would like to set a faster refresh time in _cm-rgb-monitor_.

The only change required for this is:
`@click.option('--interval', type=click.FloatRange(0.01, 60, clamp=True), default=3)`

Set interval as a FloatRange instead of IntRange. time.sleep does not care.

**Comment by gfduszynski** [comment]
Sounds reasonable 👍 

I will take this opportunity to finally add few missing features to the CLI
I will release whole thing around weekend.

Btw. have you tested shorter times ?
I don't remember but there may be a reason why I didn't include shorter times.

**Comment by mpsdskd** [comment]
Yes, works for me, just looks sightly flickery at currently 10 Hz.

**Comment by mpsdskd** [comment]
Please see https://github.com/gfduszynski/cm-rgb/pull/25

**Comment by mpsdskd** [comment]
Thanks
