### ISSUE TITLE
Not working on MSI MB

### ISSUE THREAD

**Issue by diddierh** [gfduszynski/cm-rgb#24]
I installed all the dependencies as indicated, i also added the udev rule succesfully through the indicated option "add-udev-rule", i even restarted my system to be sure the rule was applied. When i do any change the ring default sequence restarts to red but no apparent change even when i set --mode=off which should turn off the ring.

Hardware

- Wraith prism cooler.

- Motherboard MSI x470 gaming pro.

Thanks for your help.

**Comment by gfduszynski** [comment]
Hi,
Please take a look at https://github.com/gfduszynski/cm-rgb/issues/19#issuecomment-616725413
and #11 

There is a high chance that issue is caused by using both usb and rgb header cables.

**Comment by gfduszynski** [comment]
Please let me know if you solved your problem.

**Comment by diddierh** [comment]
As soon as i inplug the rgb and turn on the PC neither the fan leds nor the ring leds turn on.
As soon as i inplug the usb and plug the rgb bot set of leds turn on but i got the following trace from cm-rgb-cli

`Traceback (most recent call last):
  File "/usr/local/bin/cm-rgb-cli", line 151, in <module>
    main_group()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1146, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/bin/cm-rgb-cli", line 13, in setup_group
    'ctrl': CMRGBController(),
  File "/usr/local/lib/python3.8/dist-packages/cm_rgb/ctrl.py", line 50, in __init__
    self.__init_hid_device()
  File "/usr/local/lib/python3.8/dist-packages/cm_rgb/ctrl.py", line 57, in __init_hid_device
    raise Exception("No devices found")
Exception: No devices found
`
I forgot to mention i'm using https://github.com/nagisa/msi-rgb to change the fan leds and this works perfect when the rgb is connected, maybe it is a race condition between msi-rgb and cm-rgb but msi-rgb is not capable to set the ring leds.

Thanks.

**Comment by gfduszynski** [comment]
RGB header support is limited for this cooler, and I have close to 0 experience with this side of it.
If you want to have highest degree of control I suggest to stick with the usb connector only.
Only usb connection gives fine grained control of different zones.

As for the error, please provide output from this command after unplugging rgb header (only usb cable should be connected):
```
lsusb 
```

**Comment by unf** [comment]
Just for information, cm-rgb does work on MSI B450 A PRO && B450M PRO-VDH using Ubuntu LTS 20.04 as proposed with the USB connection. So topic of this issue can't be right ...

**Comment by gfduszynski** [comment]
I'm closing this issue due to lack of response.
Feel free to reopen it if the problems persist.

**Comment by diddierh** [comment]
> RGB header support is limited for this cooler, and I have close to 0 experience with this side of it.
> If you want to have highest degree of control I suggest to stick with the usb connector only.
> Only usb connection gives fine grained control of different zones.
> 
> As for the error, please provide output from this command after unplugging rgb header (only usb cable should be connected):
> 
> ```
> lsusb 
> ```
Sorry for not answerng so fast, i've been busy with some work, i'm still interested in making work the software with this cooler.

`Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub

Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub

Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub

Bus 001 Device 002: ID 04f3:0103 Elan Microelectronics Corp. ActiveJet K-2024 Multimedia Keyboard

Bus 001 Device 004: ID 2516:0051 Cooler Master Co., Ltd. AMD SR4 lamplight Control

Bus 001 Device 003: ID 18f8:0f97 [Maxxter] USB OPTICAL MOUSE 

Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

`

**Comment by gfduszynski** [comment]
Hi,
```
Bus 001 Device 004: ID 2516:0051 Cooler Master Co., Ltd. AMD SR4 lamplight Control
```
That's what we were looking for, perfect.
Now, make sure the rgb header cable is not connected and try to use cm-rgb-monitor
to test if it can find the cooler.

**Comment by diddierh** [comment]
This time with the usb plugged and the rgb unplugged it worked, i don't know why the last time didn't work if it was in the same state, @gfduszynski thank you very much for your help my friend, appreciated.
