### ISSUE TITLE
cm-rgb-monitor stops running after sleep mode

### ISSUE THREAD

**Issue by mpsdskd** [gfduszynski/cm-rgb#29]
As said in the headline, after waking up my computer from suspend _cm-rgb-monitor_ does not show anything anymore.

Steps to reproduce:

- Start _cm-rgb-monitor_
- suspend computer to ram
- wake computer up again
--> cm-rgb-monitor stops showing CPU load/temperature

Simple mitigation like a try/except in the eternal while loop don not work, neither does a while/True around the monitor() function.

```
if __name__ == '__main__':
    while True:
        try:
            monitor()
        except Exception as e:
            print(e)
```

Additional information:
- cm-rgb 0.1.0
- OS Kubuntu 20.04
- Python 3.8

Error message:

```
Traceback (most recent call last):
  File "/home/---/Programs/cm-rgb/scripts/cm-rgb-monitor", line 162, in <module>
    monitor()
  File "/home/---/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/---/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/---/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/---/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/---/Programs/cm-rgb/scripts/cm-rgb-monitor", line 151, in monitor
    c.apply()
  File "/home/---/.local/lib/python3.8/site-packages/cm_rgb-0.1.0-py3.8.egg/cm_rgb/ctrl.py", line 83, in apply
    return self.send_packet(self.P_APPLY)
  File "/home/---/.local/lib/python3.8/site-packages/cm_rgb-0.1.0-py3.8.egg/cm_rgb/ctrl.py", line 80, in send_packet
    return self.device.read(64)
  File "hid.pyx", line 123, in hid.device.read
OSError: read error
```

**Comment by gfduszynski** [comment]
Hello there ;)

What setup are you using to start cm-rgb-monitor ?

I'm using following systemd service file:
```
[Unit]
Description=CM RGB Monitor
BindsTo=dev-bus-usb-003-003.device
After=dev-bus-usb-003-003.device

[Service]
Type=simple
ExecStart=/usr/bin/cm-rgb-monitor --show-temp --temp-source k10temp-pci-00c3/Tdie
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
```
I've checked journalctl after suspend but no errors occur.
But thats probably because systemd stops monitor in time before suspend and then only starts after 
device is available.

My point is, if you use setup like mine with systemd the issue described should not affect you I think.

**Comment by mpsdskd** [comment]
Indeed I'm using the ~/.config/autostart/  -method. So far I did not use systemd very much.

I'll try with systemd this evening. I suspect the "Restart" might help here.

**Comment by mpsdskd** [comment]
Yes, that worked - but I had to remove the _BindsTo_ and _After_ lines and it is in /usr/local/bin for me.

I'd prefer if it was possible with the autostart folder and now cm-rgb-monitor runs as a system service (maybe I'll try as a user systemd service later), but as long as my CPU lights up everything's good^^

I still get the same error message in journalctl I posted above, but it automatically restarts.

**Comment by gfduszynski** [comment]
I'm glad you are satisfied :)
The BindsTo attribute is what prevents the error from appearing as per [manual](https://www.freedesktop.org/software/systemd/man/systemd.unit.html) it stops the service
when the device is disconnected from the system.

**Comment by dominalien** [comment]
I'm starting cm-rgb-monitor using systemd in user mode (with --user) now, too, and the BindsTo and After lines don't work for me either; the service hangs on start complaining about unmet dependency (I did amend the lines as per my system ofc). I haven't been able to find any info on how to reference the usb device (I'd rather use its ID than bus/device) and cm-rgb-monitor works fine on resume from sleep, so leaving as is...

**Comment by gfduszynski** [comment]
@dominalien 
My current udev rule 
```
SUBSYSTEM=="usb", ATTR{idVendor}=="2516", ATTR{idProduct}=="0051", TAG+="uaccess", TAG+="udev-acl", SYMLINK+="cm-rgb", TAG+="systemd"
```

My current systemd unit
```
[Unit]
Description=CM RGB Monitor
BindsTo=dev-cm\x2drgb.device
After=dev-cm\x2drgb.device

[Service]
Type=simple
ExecStart=/usr/bin/cm-rgb-monitor --show-temp --temp-source k10temp-pci-00c3/Tdie --show-cpu-frequency --brightness 2
ExecStopPost=/usr/bin/cm-rgb-cli restore
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
```

If it works for you I should update the wiki, ``ExecStopPost`` is used to resume saved animation for boot / shutdown.

**Comment by dominalien** [comment]
Yes, the service starts now and from limited testing continues working after resume from suspend.
