### ISSUE TITLE
[FR] Control Prism via Project Aurora

### ISSUE THREAD

**Issue by Hukuma1** [gfduszynski/cm-rgb#31]
Heya! Stumbled upon this repo after searching for people who were fed up to control 1 light from proprietary CM software. Thank you for taking the time to make this.

Was wondering if it would be possible to export the ability to change lights of all the zones (ring, fan, logo) to a great all-in-one project that links and controls RGB peripherals (https://github.com/antonpup/Aurora)?

**Comment by gfduszynski** [comment]
Hi :)
I think it would require a complete rewrite to .net
I'll take a look how it works.

**Comment by daydy16** [comment]
Would be amazing! At the moment I'm using Chroma Sync with the original software and project aurora 🤮

**Comment by CalcProgrammer1** [comment]
OpenRGB/Aurora integration is mostly implemented in a development branch and OpenRGB supports the Wraith Prism as well.  It's not using this project but it is an option you can try.  I haven't tested it on the Prism as my Prism is in my Linux-only box and Aurora only works on Windows, but it works on other single-LED zone devices I have.
