### ISSUE TITLE
CPU Temp in Windows?

### ISSUE THREAD

**Issue by vexersa** [gfduszynski/cm-rgb#34]
Thanks for this!

I'm trying to get the temp sensors working in Windows. 
Any advice?

**Comment by gfduszynski** [comment]
Hi!

There is a way to achieve this, but it's not supported in current version.

If you know a little bit of python you could try to modify cm-rgb-monitor 
Take a look at this example https://gist.github.com/chand1012/1ae6f3703089526b3ac9148e8f79dccb

**Comment by vexersa** [comment]
Cool, thanks!

Perhaps I can contribute once I've implemented.

**Comment by vexersa** [comment]
Great. Got it to work!

Could you tell me which variable determines the CPU temp sampling/LED colour change update rate? I'd like to make this as fast as possible.

**Comment by gfduszynski** [comment]
Awsome :)
Basically the loop is regulated by the sleep statement at the end of the loop.
```python
time.sleep(interval)
```
Interval can be manipulated by passing an argument to the script.

Please note that user @mpsdskd is working currently on pull request that will affect the loop substantially https://github.com/gfduszynski/cm-rgb/pull/33

**Comment by mpsdskd** [comment]
I'm afraid it's not THAT simple, as psutil under Windows does not seem to have sensors_temperatures()

https://pypi.org/project/psutil/ <-- that's the library used for reading out temperatures in the latest version of my fork.

Edit: I read @gfduszynski's post with  https://gist.github.com/chand1012/1ae6f3703089526b3ac9148e8f79dccb, so there is already a solution to getting the temperature in windows. So just forget about psutil.

**Comment by gfduszynski** [comment]
Yeah, there need's to be OS detection in this script if its to work with windows properly.

**Comment by vexersa** [comment]
I had to shoehorn some of @gfduszynski 's solution to get it to work but it does work. 

@mpsdskd, is your fork ready for testing on Windows? 

Can I help with anything?

**Comment by mpsdskd** [comment]
It is.

I guess for it to work on windows it first needs to check which os it's running on and if it's windows the temperature measurement needs to come from a different source. 

Unfortunately I cannot test anything on windows.
Does everything else work? 
Then implementing the fix should be quite easy with the linked code snippet from above.

**Comment by mpsdskd** [comment]
To be more specific:

https://www.github.com/mpsdskd/cm-rgb/tree/master/scripts%2Fcm-rgb-monitor

In line 102 it gets the temperature value and stores it in "t". 
As soon as there is a temperature value there it should work.


```
If windows:
     t = your_new_windows_get_temperature_function()
else:
    t = psutil.....
```

**Comment by gfduszynski** [comment]
#35 has been merged

**Comment by mpsdskd** [comment]
I prepared the monitor in my fork to work with windows. 
Now it needs a function to read temperature on windows and testing it, which I cannot do - you would just have to fill the function `get_temperature_windows()` in https://github.com/mpsdskd/cm-rgb/blob/master/scripts/cm-rgb-monitor.

**Comment by vexersa** [comment]
Works good here. I added the wmi based code shared previously into the
get_temperature_windows() function. Everything seems to work as expected.
Would it be possible to add smoothing to the fan/frequency colour changes?

How would I run the script with all features turned on, eg: Fan shows temp,
logo shows frequency, ring shows CPU use. I have tried appending options
but when doing so not all options are respected.

**Comment by mpsdskd** [comment]
Yes, smoothing would also be quite simple using the same code used for frequency smoothing.
I think we could simply use the same smoothing parameter.

Could you share your working get_temperature_windows() function?

Running the script with --help gives information about available parameters.

**Comment by mpsdskd** [comment]
cm-rgb-monitor --verbose --show-temp --show-cpu-frequency

**Comment by gfduszynski** [comment]
@vexersa do you want to create your own pull request with the get_temperature_windows ?

**Comment by vexersa** [comment]
@gfduszynski I'll so so asap. Having some issues with the script I'm working out.

**Comment by gfduszynski** [comment]
Hi :) any progress with the pull request @vexersa ?

**Comment by vexersa** [comment]
Hi !

Apologies for the absence. Working for yourself has its perks and it's
downfalls. Unfortunately this week has absolutely nuked my free time.

I will get to this as soon as I'm able.
