### ISSUE TITLE
OSError: open failed

### ISSUE THREAD

**Issue by xukeyan** [gfduszynski/cm-rgb#37]
I googled this issue and I believe I got an usb device permission issue. I hope someone can help and thanks in advance.

I ran the 'cm-rgb-cli add-udev-rule' in the installation section but I am not sure if it was effective or not. Here is what I got:
 ```
'SUBSYSTEM=="usb", ATTR{idVendor}=="2516", ATTR{idProduct}=="0051", TAG+="uaccess", TAG+="udev-acl"' > /etc/udev/rules.d/60-cm-rgb.rules
Created /etc/udev/rules.d/60-cm-rgb.rules
udev should apply new rule automatically. If not, try running 'sudo udevadm trigger' 
```
when I ran any cm-rgb-cli command, I got the OSError: open failed issue:
```
self.device.open_path(device_list[0]["path"])
File "hid.pyx", line 72, in hid.device.open_path
OSError: open failed
```
my system is Ubuntu 20.04 system. Again, thanks for any helps.

**Comment by xukeyan** [comment]
Here is how I resolved it: --refer to [https://github.com/gfduszynski/cm-rgb/issues/7](url) (I had a very similar with that link, I neither cannot simply use sudo to call the CLI command.)

0. reinstall hid in [https://github.com/trezor/cython-hidapi](url)
1. reinstalled it with `sudo pip install cm-rgb `
2. then `sudo pip install --upgrade cm-rgb`

Now I can use `sudo cm-rgb-cli set logo --mode=off save` to turn off the rgb!

Question: I don't know what did this command do, why did it help me with this issue? Could you please explain a little bit? Thanks!

**Comment by gfduszynski** [comment]
Hi, I'm not absolutely sure whats the reason behind this.
Did you reboot your PC in between attempts ?
If so, then perhaps udev rule has only started working after reboot.
