### ISSUE TITLE
Installation problems on Ubuntu 20.04 LTS 

### ISSUE THREAD

**Issue by distributorofpain** [gfduszynski/cm-rgb#42]
Tried to install and had to go back and install lots of packages before pip would complete:

apt-get install python-dev libusb-1.0-0-dev libudev-dev libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential

then tried run pip3 install cm-rgb and also using this git repository, no dice.

I can run the command:
cm-rgb-cli set logo --mode=off save

but the light doesnt turn off.  I did run the lsusb | grep 2516:0051 command and got:

Bus 001 Device 004: ID 2516:0051 Cooler Master Co., Ltd. AMD SR4 lamplight Control

Version shows 0.3.4 and the CLI version shows V1.01.00

I have three machines, exact same boards/config, all three do the same thing.  Thoughts?

**Comment by gfduszynski** [comment]
Hi,
Please check that you **don't** have RGB cable connected.
RGB cable overrides settings from the USB.

**Comment by distributorofpain** [comment]
wow, did not know that!  Unplugged LED cable from all three boards, light on cooler went off immediately!  Guessing this is why the windows prisim tool never worked either.  The MB has a control but it only turns the board light off.  Never even tried that.

Thanks!  Resolved.

**Comment by distributorofpain** [comment]
BTW:  Thanks for making this!!

**Comment by gfduszynski** [comment]
Thank you :+1: 
I'm glad it has worked for you :)
