### ISSUE TITLE
Reset original rgb effects

### ISSUE THREAD

**Issue by ugiete** [gfduszynski/cm-rgb#44]
Is it possible to reset the original rgb effects after setting static rgb on cm-rgb-gui?

**Comment by gfduszynski** [comment]
Hi,
There are at least 2 ways:
- https://github.com/gfduszynski/cm-rgb/issues/21
- Manually issuing a command that sets every zone to the factory settings, however I don't have actual command that does that on hand.

Also If you have not used ``save`` parameter you may be able to issue restore command.

**Comment by ugiete** [comment]
Thanks for your reply and great job on this project, the #21 and #20 helped me.
