### ISSUE TITLE
ModuleNotFoundError: No module named 'hid'

### ISSUE THREAD

**Issue by Graeme22** [gfduszynski/cm-rgb#47]
Running on Ubuntu 20.04. Here's the trace:

```
sudo ./cm-rgb-cli add-udev-rule
Traceback (most recent call last):
  File "./cm-rgb-cli", line 3, in <module>
    from cm_rgb.ctrl import LedChannel, LedMode, CMRGBController
  File "/home/graeme/Documents/cm-rgb/scripts/cm_rgb/ctrl.py", line 1, in <module>
    import hid
ModuleNotFoundError: No module named 'hid'
```

However, I know that hid is already installed, as I can run `import hid` in the interpreter just fine.

Would appreciate help on this, I'm pretty stuck!

**Comment by gfduszynski** [comment]
Hi,
Please run this without sudo. Script should ask for password while executing.

The reason it's not working like that is because packages have been installed only for your user and not for root.

Hope this helps

**Comment by Graeme22** [comment]
I ended up using [WraithMaster](https://gitlab.com/serebit/wraith-master/-/releases) which had a working executable. Thank you for your help though.
