### ISSUE TITLE
ArchLinux dependencies

### ISSUE THREAD

**Issue by HarlemSquirrel** [gfduszynski/cm-rgb#48]
I had to install `libusb` and `hidapi` only before installing with pip.

```sh
sudo pacman -S libusb hidapi

pip install --user --upgrade cm-rgb
```

**Comment by gfduszynski** [comment]
Hi,
That aligns well with the manual in the wiki:
https://github.com/gfduszynski/cm-rgb/wiki/1.-Installation-&-Configuration

Or did some problems go beyond what is described ?

**Comment by HarlemSquirrel** [comment]
What I'm saying is that I did not need to install any AUR packages.

**Comment by gfduszynski** [comment]
Aah I see now, I'll update the wiki.
Thank you :)
