### ISSUE TITLE
cm-rgb-cli: command not found

### ISSUE THREAD

**Issue by tokejuhoklee** [gfduszynski/cm-rgb#51]
After installing with pip(had to use pip3?), I keep getting this error:

system@myuser:/usr/local/bin$ cm-rgb-cli add-udev-rule
cm-rgb-cli: command not found

when I pip3 list I see cm-rgb-cli listed, but I seem to be unable to access it. I know it may be a bit unrelated. but I'm unable to figure out what to do

**Comment by gfduszynski** [comment]
Hi,
This is typically associated with running pip with sudo. 
If you ran something like ``sudo pip3 install cm-rgb`` this would only make the command available for root.

Anyway that's how I understand it. 
If you did use sudo try without.
