### ISSUE TITLE
Udev rule for macOS

### ISSUE THREAD

**Issue by VeliborS** [gfduszynski/cm-rgb#52]
Hello,

I have hackintosh machine with Ryzen 7 3700, I did install everything as required, however as far as I understood there is no udev for mac searching on Google and I cant add cm-rgb-cli add-udev-rule to access device.
I'm I missing something?

**Comment by gfduszynski** [comment]
Hi,

This is tricky.
https://stackoverflow.com/questions/26920339/whats-the-udev-like-thing-on-osx-and-how-does-it-work

I don't have access to Mac OS and experience necessary to solve this.
Someone would need to chip in on this.

udev rule is only there to provide user access to the usb device, so no body has to ``chmod 777`` on their usb devices or run with sudo. Did you check if that is at all necessary on osx ?

**Comment by gfduszynski** [comment]
Btw if you want to set a fixed style and save it to your cooler then running it once with sudo or similar is ok.
I would be more concerned if you would like to run it as a service with ``cm-rgb-monitor``, only then I would pursue non root access.

**Comment by VeliborS** [comment]
Hello gfduszynski,

Please close this issue, it is partially working,no udev needed, however, due to lack of time can't research further on this and I have installed Windows on another disk, running a dual boot with macOS Big Sur so I installed on Windows CM app and managing LED lights through it.
Thank you for your time.
