### ISSUE TITLE
problematic project name

### ISSUE THREAD

**Issue by ausil** [gfduszynski/cm-rgb#56]
In #53 I was attempting to clean things up because packaging up the project as it is is messy and problematic due to the inconsistency between the project name cm-rgb and the python module cm_rgb there are ways to make module loading working with a - in the name but it is not recommended. Therefore, it would be better to rename the project to cm_rgb or cmrgb or something else where there is consistency between the module name and the project name. I figured it is best to file an issue for a discussion.

**Comment by gfduszynski** [comment]
I agree this needs fixing.
I'm planning to change the project name [``setup.py``] to cm_rgb to match the current dir structure.
I've found a guide which I intend to follow on resolving this issue:
https://github.com/simonw/pypi-rename

Is this enough to make fedora packaging clean ?

**Comment by ausil** [comment]
I think it would be fine, as long as the tarball is cm_rgb-<version>.tar.gz and the directory in it. 
the mixed locations break the macros used in packaging, it can be worked around, it is just not the normal behaviour. I was able to achieve what I wanted in disabling all the lights, I am just trying to make it easier for fedora users to manage going forward.

**Comment by gfduszynski** [comment]
Take a look https://pypi.org/project/cm-rgb/0.3.5/

**Comment by ausil** [comment]
looks great, thanks
