### ISSUE TITLE
PySensor required?

### ISSUE THREAD

**Issue by rhoriguchi** [gfduszynski/cm-rgb#57]
I just looked at the source of `cm-rgb-monitor` and noticed everything is called with `psutil`. Is `PySensor` required like stated in [docs](https://github.com/gfduszynski/cm-rgb/wiki/3.-Monitor-usage#temperature-display).

**Comment by gfduszynski** [comment]
It looks like you are right, good find :+1:  
We must have forgot to remove this dependency when we switched to ``psutil``.

I'll take care of it over the weekend.
