### ISSUE TITLE
Error running cm-rgb-cli

### ISSUE THREAD

**Issue by cby120** [gfduszynski/cm-rgb#61]
Dear gfduszynski: 

Hello !

I'm suffering an error running cm-rgb-cli, **ver 0.3.6**. No matter what param I give, it raises the error:
```
Traceback (most recent call last):
  File "/usr/local/bin/cm-rgb-cli", line 23, in <module>
    @setup_group.resultcallback()
AttributeError: 'Group' object has no attribute 'resultcallback'
```
I'm running cm-rgb-cli in multi-user mode. The environment is Debian 11, kernel 5.10.0, python 3.9, package **click is version 8.1.3**. It's very likely that some of the packages have been refactored and mine are not in desirable version. Could you please check this out? If any more information is required, please tell me. 

Thank you very much!

**Comment by gfduszynski** [comment]
Hello cby120:
I've found similar problem: https://github.com/trezor/trezor-firmware/issues/2199

Please try replicate the following: https://github.com/trezor/trezor-firmware/issues/2199#issuecomment-1151632985
I'm guessing it will work after editing ``/usr/local/bin/cm-rgb-cli``

What I don't understand is why, I also have **click**  in the same version as you, however python 3.10.5.
Let me know if it helps, I'll release a fix.

**Comment by cby120** [comment]
It works! Seems it is just an API spelling difference. I might be that different version of Python have different package maintenance leaving such difference in API naming. Thank you again, it helps!
