### ISSUE TITLE
The ring can not be controlled

### ISSUE THREAD

**Issue by Catman100** [gfduszynski/cm-rgb#62]
I have the problem that the ring can not be controlled. In addition, it does not work that I can turn off the logo and the ring.

**Comment by gfduszynski** [comment]
Please verify that only USB connection to the cooler is provided, connecting RGB header can lead to unexpected results.
Checkout: https://github.com/gfduszynski/cm-rgb/wiki/1.-Installation-&-Configuration

**Comment by Catman100** [comment]
Yes Only the USB Header is connected

**Comment by gfduszynski** [comment]
Please paste the failing command, I'll try to run it on mine setup just to make sure.
Additionally paste the result of ``cm-rgb-cli --version``

**Comment by Catman100** [comment]
cm-rgb-cli set logo --mode=off save

V1.01.00

**Comment by Zampalot** [comment]
Herr Catman100 sie sind sehr schlecht.

**Comment by gfduszynski** [comment]
Sorry for the long delay.

You have the same version of firmware, command works for me.

Maybe ``cm-rgb-cli restore`` will help, but I'm out of ideas.
