### ISSUE TITLE
__init_hid_device : Exception: No devices found

### ISSUE THREAD

**Issue by arhuaco** [gfduszynski/cm-rgb#9]
Hello there. The script cannot list USB devices. What can I try?

**Comment by gfduszynski** [comment]
Hi,
Try ``lsusb`` and look for 
`` Bus 003 Device 003: ID 2516:0051 Cooler Master Co., Ltd.  ``

Verify that usb cable is properly connected to your cooler and that rgb header is not

**Comment by arhuaco** [comment]
Thanks. I just learned that the USB cable is needed and that I don't have it installed. They didn't plug it when I bought the PC and it's not in the boxes. I'll try again when I get the cable.
